### ISSUE TITLE
Hi, please add new version for windows

### ISSUE THREAD

**Issue by winnery2022** [XopMC/keyhunt-win#11]
Hi, please add new version for windows. Tnx.

**Comment by XopMC** [comment]
> Hi, please add new version for windows. Tnx.

👌

**Comment by XopMC** [comment]
> Hi, please add new version for windows. Tnx.

Updated!

**Comment by winnery2022** [comment]
I don't know why the old version not works. The new one does not start more than 1 mode (

**Comment by XopMC** [comment]
🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by winnery2022** [comment]
C:\Users\Winnery\Desktop\Keyhunt_19.05.23\MinGW>keyhunt.exe -m bsgs -b 125 -f 11.txt -s 1 -t 2 -k 2048 -S -R

C:\Users\Winnery\Desktop\Keyhunt_19.05.23\MinGW>goto :loop

C:\Users\Winnery\Desktop\Keyhunt_19.05.23\MinGW>keyhunt.exe -m bsgs -b 125 -f 11.txt -s 1 -t 2 -k 2048 -S -

**Comment by XopMC** [comment]
keyhunt.exe -m bsgs -f 125pub.txt -l compress -R -b 125 -6 -n 0x400000000000 -k 8192 -S -q -s 600 -t 71 
Successfully launched with 250GB RAM

**Comment by XopMC** [comment]
![image](https://github.com/XopMC/keyhunt-win/assets/89750173/1775a3b2-2ad8-4bf4-a88a-365db2bffcd0)

**Comment by winnery2022** [comment]
Cool . Don't know why at me not working.
