### ISSUE TITLE
Update keyhunt

### ISSUE THREAD

**Issue by phrutis** [XopMC/keyhunt-win#4]
Привет ХорМС! 
Обнови версию keyhunt для Windows x64
Подскажи как скомпилировал? 
У меня не получилось (

**Comment by sotiz0** [comment]
Дико плюсую, только версия от XopMC у меня заводится корректно

**Comment by phrutis** [comment]
Ещё работают сборки от [kanhavishva](https://github.com/kanhavishva/keyhunt/releases), но они старые. В обеих у меня проблема с -к, -k 2048 это мало, -k 4096 много (бьет ошибку)
Вечером буду пробовать через unbuntu.

**Comment by XopMC** [comment]
> Привет ХорМС! Обнови версию keyhunt для Windows x64 Подскажи как скомпилировал? У меня не получилось (

Салют!
Прошу прощения, я немного вылетел из жизни, я после больницы 

Компилировал с помощью MinGW
С новыми версиями сложнее, Альберто жалуется что тяжело поддерживать один код для 3 устройств 

Я обязательно вернусь к keyhunt, как поправлю здоровье

**Comment by phrutis** [comment]
XopMC поправляйся, кроме тебя никто не может.

**Comment by XopMC** [comment]
> XopMC поправляйся, кроме тебя никто не может.

Обновил, тестируйте
