### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dem10** [XopMC/keyhunt-win#5]
The program worked for several days and gave an error. Minikey mode.
![123](https://user-images.githubusercontent.com/24973894/145673300-58e17edc-1582-478d-80b2-617d63a1fb98.png)

**Comment by XopMC** [comment]
Странно, впервые сталкиваюсь с такой ошибкой...

Такая ошибка возникает при чтении или записи в недоступный адрес в памяти.

не могу сказать что это баг именно keyhunt, может вы используете старый CPU ?

**Comment by dem10** [comment]
CPU конечно не совсем новый но Райзен 7 1700.Я запустил keyhunt ещё раз с такими же параметрами.Ситуация повторилась-инструмент работает нормально примерно 7 дней  и вновь крашится с этой ошибкой.Попробую отключить вывод потоков.Возможно это он дает сбой но я не уверен.

**Comment by XopMC** [comment]
> CPU конечно не совсем новый но Райзен 7 1700.Я запустил keyhunt ещё раз с такими же параметрами.Ситуация повторилась-инструмент работает нормально примерно 7 дней и вновь крашится с этой ошибкой.Попробую отключить вывод потоков.Возможно это он дает сбой но я не уверен.

Попробуйте обновлённую версию, может быть ошибки уже не будет.
